<?php

/**
 * module.module
 *
 * module
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\countdown\Element\CountdownRenderElement;

/**
 * Implements hook_help().
 */
function countdown_help($route_name,RouteMatchInterface $route_match) {
  switch ($route_name) {
  case 'help.page.countdown':
    return '
		  <h2>Countdown</h2>
	    ';
  }
}

/**
 * Implements hook_theme().
 */
function countdown_theme($existing,$type,$theme,$path) {

  return [
    'countdown_widget' => [
      'variables' => [
        'attributes' => [
          'class' => 'countdown-widget',
        ],
        'countdown_date' => CountdownRenderElement::makeDefaultCountdownDate(),
        'countdown_settings' => [
          'format' => 'clock',
          'include_seconds' => true,
        ],
      ],
    ],
  ];
}

/**
 * Local Variables:
 * mode:php
 * End:
 */
